# Generated by Django 2.1.7 on 2019-03-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sku', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=120)),
                ('author', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=20)),
            ],
        ),
    ]
